server:
  port: 8080
  shutdown: graceful

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true # 데이터 insert 지연
    open-in-view: false
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/dream?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: my_user
    password: my_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  lifecycle:
    timeout-per-shutdown-phase: 30s
