server:
  port: 8080
  shutdown: graceful

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  lifecycle:
    timeout-per-shutdown-phase: 30s
